### ISSUE TITLE
vbelltimeout is in ms - not 0/1

### ISSUE THREAD

**Issue by avih** [QDesjardin/qdest-0.8.1#1]
Hi, I noticed that you use the visual bell patch (which I wrote, as well as the boxdraw patch BTW), and noticed that you set `vbelltimeout = 1`. However, its value is in millisec like other config timeouts, and not 0/1.

I'd recommend a value of 100 or 150 ms.

Just FYI.

**Comment by QDesjardin** [comment]
Fixed, thanks.
